version: '3.8'

services:
  app:
    build: scripts/docker/go
    volumes:
      - ./:/app
    ports:
      - ${PORT}:${PORT}
    command: CompileDaemon --build="go build -o ./build/main ." --command=./build/main